"""Pydantic request/response models for the Phase 12 organizations endpoints.

Models stay deliberately thin: validation lives on the Pydantic schema, and
business logic lives in ``organizations.service``. Role is constrained via a
``Literal`` so the FastAPI request validator rejects unknown values before they
ever reach the database (where they would surface as a Postgres
``invalid_text_representation`` against the ``public.org_role`` ENUM).
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, EmailStr, Field, StringConstraints


# Mirrors public.org_role in supabase/migrations/20260605000001_organizations.sql.
OrgRoleLiteral = Literal["owner", "scientist", "viewer"]
SelfDowngradeRoleLiteral = Literal["scientist", "viewer"]


# Pydantic-v2 form for trimmed, length-bounded org names. Bounds match the
# database CHECK constraint (name_not_blank) and the UI's input maxlength.
OrgName = Annotated[
    str,
    StringConstraints(strip_whitespace=True, min_length=1, max_length=100),
]


class CreateOrgRequest(BaseModel):
    """Body for POST /organizations.

    Name is trimmed and length-bounded so the database-side
    ``name_not_blank`` CHECK constraint never fires from a UI typo.
    """

    name: OrgName


class OrgResponse(BaseModel):
    """Response shape for any single-org endpoint.

    Includes the caller's role so the frontend can gate billing UI without a
    second round-trip.
    """

    id: str
    name: str
    role: OrgRoleLiteral
    is_personal: bool


class ListMineResponse(BaseModel):
    """Envelope for GET /organizations/mine."""

    orgs: list[OrgResponse]


class InviteRequest(BaseModel):
    """Body for POST /organizations/{org_id}/invitations."""

    email: EmailStr
    role: OrgRoleLiteral


class TransferRequest(BaseModel):
    """Body for POST /organizations/{org_id}/members/transfer.

    ``new_self_role`` is restricted to ``scientist`` or ``viewer`` since
    transferring ownership only makes sense when the current owner is also
    self-demoting (otherwise the org would have two owners — which is allowed
    via the role-update endpoint but is NOT the contract of "transfer").
    """

    target_user_id: str
    new_self_role: SelfDowngradeRoleLiteral


class AcceptInviteRequest(BaseModel):
    """Body for POST /invitations/accept.

    Token is the URL-safe base64 string generated by ``secrets.token_urlsafe(32)``
    which yields a 43-character output. We allow up to 64 characters to be
    forward-compatible if the entropy budget grows.
    """

    token: str = Field(min_length=32, max_length=64)


class MemberRoleUpdate(BaseModel):
    """Body for PATCH /organizations/{org_id}/members/{user_id}."""

    role: OrgRoleLiteral


class UpdateOrgRequest(BaseModel):
    """Body for PATCH /organizations/{org_id}."""

    name: OrgName
