-- ============================================================================
-- Phase 12: Teams & Organizations
-- ============================================================================
-- Adds organizations, organization_memberships, organization_invitations tables.
-- Moves stripe_customer_id from public.users to public.organizations.
-- Replaces jobs_own RLS policy with organization-scoped policy.
-- Backfills a personal organization for every existing user.
--
-- This migration is ONLINE-SAFE: all schema changes are additive and the
-- backfill runs in the same transaction as the cutover. Apply via Supabase
-- CLI (Phase 11 D-06 makes this the predeploy hook).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. ENUM for roles
-- ----------------------------------------------------------------------------

CREATE TYPE public.org_role AS ENUM ('owner', 'scientist', 'viewer');

COMMENT ON TYPE public.org_role IS
    'Organization member role. owner = billing+admin; scientist = run+view jobs; viewer = read-only.';

-- ----------------------------------------------------------------------------
-- 2. organizations
-- ----------------------------------------------------------------------------

CREATE TABLE public.organizations (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name                TEXT NOT NULL,
    is_personal         BOOLEAN NOT NULL DEFAULT FALSE,
    stripe_customer_id  TEXT UNIQUE,
    created_by          UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT name_not_blank CHECK (length(btrim(name)) > 0)
);

COMMENT ON TABLE public.organizations IS
    'Tenant boundary. Every job, billing event, and RLS scope is keyed on this. '
    'is_personal=true means the auto-created personal org for a solo user.';

CREATE INDEX idx_orgs_stripe_customer ON public.organizations(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 3. organization_memberships
-- ----------------------------------------------------------------------------

CREATE TABLE public.organization_memberships (
    organization_id     UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    user_id             UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    role                public.org_role NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (organization_id, user_id)
);

CREATE INDEX idx_memberships_user ON public.organization_memberships(user_id);
CREATE INDEX idx_memberships_org_role ON public.organization_memberships(organization_id, role);

COMMENT ON TABLE public.organization_memberships IS
    'Many-to-many user <-> organization with role. Last-owner DELETE protection '
    'enforced by the trigger below. Personal orgs always have exactly 1 owner row.';

-- ----------------------------------------------------------------------------
-- 4. organization_invitations
-- ----------------------------------------------------------------------------

CREATE TABLE public.organization_invitations (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id     UUID NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    email               TEXT NOT NULL,
    role                public.org_role NOT NULL,
    token               TEXT NOT NULL UNIQUE,
    invited_by          UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    expires_at          TIMESTAMPTZ NOT NULL,
    accepted_at         TIMESTAMPTZ,
    accepted_by         UUID REFERENCES public.users(id) ON DELETE SET NULL,
    revoked_at          TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT no_duplicate_pending UNIQUE (organization_id, email)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_invitations_org ON public.organization_invitations(organization_id) WHERE accepted_at IS NULL AND revoked_at IS NULL;
CREATE INDEX idx_invitations_email ON public.organization_invitations(lower(email)) WHERE accepted_at IS NULL AND revoked_at IS NULL;

COMMENT ON COLUMN public.organization_invitations.token IS
    'Single-use URL-safe random token (32 bytes base64url). Generated by the backend, never stored in plaintext anywhere else.';

-- ----------------------------------------------------------------------------
-- 5. Last-owner protection trigger
-- ----------------------------------------------------------------------------
-- DB-enforced invariant: an organization always has at least one owner.
-- App-level checks alone are insufficient against concurrent DELETEs.

CREATE OR REPLACE FUNCTION public.protect_last_owner()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    remaining_owners INT;
BEGIN
    -- For UPDATE: only fire if the role was demoted FROM owner
    IF (TG_OP = 'UPDATE' AND OLD.role = 'owner' AND NEW.role <> 'owner')
       OR (TG_OP = 'DELETE' AND OLD.role = 'owner')
    THEN
        SELECT count(*) INTO remaining_owners
        FROM public.organization_memberships
        WHERE organization_id = OLD.organization_id
          AND role = 'owner'
          AND user_id <> OLD.user_id;
        IF remaining_owners = 0 THEN
            RAISE EXCEPTION 'Cannot remove or demote last owner of organization %', OLD.organization_id
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER protect_last_owner_trigger
    BEFORE UPDATE OR DELETE ON public.organization_memberships
    FOR EACH ROW
    EXECUTE FUNCTION public.protect_last_owner();

-- ----------------------------------------------------------------------------
-- 6. RLS helper functions — MUST be plpgsql, NOT sql, or they inline & recurse
-- ----------------------------------------------------------------------------
-- Postgres inlines simple SQL functions during query planning. Inlined SECURITY
-- DEFINER loses its context and RLS re-applies, causing "infinite recursion
-- detected in policy" on any policy that queries organization_memberships.
-- PL/pgSQL functions are NEVER inlined, so SECURITY DEFINER works as intended.
-- See: https://dev.to/bairescodeai/infinite-recursion-in-postgres-rls-a-security-definer-gotcha-1916

CREATE OR REPLACE FUNCTION public.is_member_of(_org_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.organization_memberships
        WHERE organization_id = _org_id AND user_id = auth.uid()
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.has_role_in(_org_id UUID, _required public.org_role[])
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.organization_memberships
        WHERE organization_id = _org_id
          AND user_id = auth.uid()
          AND role = ANY(_required)
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.is_member_of(UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role_in(UUID, public.org_role[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_member_of(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role_in(UUID, public.org_role[]) TO authenticated;

-- ----------------------------------------------------------------------------
-- 7. RLS policies on new tables
-- ----------------------------------------------------------------------------

ALTER TABLE public.organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_invitations ENABLE ROW LEVEL SECURITY;

-- Members can SELECT their orgs; owners can UPDATE.
CREATE POLICY orgs_select_members ON public.organizations
    FOR SELECT USING (public.is_member_of(id));

CREATE POLICY orgs_update_owners ON public.organizations
    FOR UPDATE USING (public.has_role_in(id, ARRAY['owner']::public.org_role[]));

-- INSERT requires the creator to set themselves as owner in the same request.
-- The router handles this in a single transaction via the create_organization
-- SECURITY DEFINER RPC. We allow any authenticated user to insert (then RLS on
-- memberships gates the matching insert).
CREATE POLICY orgs_insert_any_authenticated ON public.organizations
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Memberships: members can read all rows for orgs they belong to; owners write.
CREATE POLICY memberships_select_members ON public.organization_memberships
    FOR SELECT USING (public.is_member_of(organization_id));

CREATE POLICY memberships_write_owners ON public.organization_memberships
    FOR ALL USING (public.has_role_in(organization_id, ARRAY['owner']::public.org_role[]))
    WITH CHECK (public.has_role_in(organization_id, ARRAY['owner']::public.org_role[]));

-- Invitations: members can SELECT pending invites for their org; owners write.
CREATE POLICY invitations_select_members ON public.organization_invitations
    FOR SELECT USING (public.is_member_of(organization_id));

CREATE POLICY invitations_write_owners ON public.organization_invitations
    FOR ALL USING (public.has_role_in(organization_id, ARRAY['owner']::public.org_role[]))
    WITH CHECK (public.has_role_in(organization_id, ARRAY['owner']::public.org_role[]));

-- ----------------------------------------------------------------------------
-- 8. Add organization_id to public.jobs, then backfill, then enforce NOT NULL
-- ----------------------------------------------------------------------------

ALTER TABLE public.jobs ADD COLUMN organization_id UUID REFERENCES public.organizations(id) ON DELETE CASCADE;

-- 8a. Backfill: create one personal org per existing user, with the user as owner.
DO $$
DECLARE
    u RECORD;
    new_org_id UUID;
BEGIN
    FOR u IN
        SELECT id, email, stripe_customer_id, created_at
        FROM public.users
    LOOP
        INSERT INTO public.organizations
            (name, is_personal, stripe_customer_id, created_by, created_at)
        VALUES
            (
                COALESCE(NULLIF(split_part(u.email, '@', 1), ''), 'Personal')
                || ' (Personal)',
                TRUE,
                u.stripe_customer_id,
                u.id,
                u.created_at
            )
        RETURNING id INTO new_org_id;

        INSERT INTO public.organization_memberships (organization_id, user_id, role, created_at)
        VALUES (new_org_id, u.id, 'owner', u.created_at);

        UPDATE public.jobs SET organization_id = new_org_id WHERE user_id = u.id;
    END LOOP;
END $$;

-- 8b. Now safe to enforce NOT NULL.
ALTER TABLE public.jobs ALTER COLUMN organization_id SET NOT NULL;

-- 8c. Helpful index for org-scoped job lists.
CREATE INDEX idx_jobs_org_created ON public.jobs(organization_id, created_at DESC);

-- ----------------------------------------------------------------------------
-- 9. Replace jobs_own RLS policy
-- ----------------------------------------------------------------------------

DROP POLICY IF EXISTS jobs_own ON public.jobs;

CREATE POLICY jobs_org_members ON public.jobs
    FOR SELECT USING (public.is_member_of(organization_id));

-- INSERT/UPDATE require scientist or owner (viewers are read-only).
CREATE POLICY jobs_write_active ON public.jobs
    FOR INSERT WITH CHECK (
        public.has_role_in(organization_id, ARRAY['owner','scientist']::public.org_role[])
    );

CREATE POLICY jobs_update_active ON public.jobs
    FOR UPDATE USING (
        public.has_role_in(organization_id, ARRAY['owner','scientist']::public.org_role[])
    );

-- ----------------------------------------------------------------------------
-- 10. Update job_candidates RLS — org-scope through jobs.organization_id
-- ----------------------------------------------------------------------------
-- Original policy name confirmed by reading 20260319000002_billing_and_results.sql:31-34
-- (policy name was candidates_own; matches DROP target below).

DROP POLICY IF EXISTS candidates_own ON public.job_candidates;
CREATE POLICY candidates_org ON public.job_candidates
    FOR ALL USING (
        public.is_member_of(
            (SELECT organization_id FROM public.jobs WHERE id = job_candidates.job_id)
        )
    );

-- Sessions stay user-scoped (a conversation in /chat is private to the
-- individual scientist; not shared with the org). Sessions also fan out into
-- a job, which IS org-shared via jobs.organization_id — so the conversation
-- privacy boundary stops at the session_messages level and the job becomes
-- org-visible the moment it's launched.
-- No change to sessions_own / session_messages_own policies.

-- ----------------------------------------------------------------------------
-- 11. Deprecate users.stripe_customer_id (drop happens in Plan 12-06)
-- ----------------------------------------------------------------------------
-- The backfill above already copied stripe_customer_id to the personal org.
-- For ONLINE safety, drop in a SECOND migration after backend deploys.

COMMENT ON COLUMN public.users.stripe_customer_id IS
    'DEPRECATED — Phase 12 moved Stripe to public.organizations.stripe_customer_id. '
    'This column will be dropped in 20260606000001 once backend migration is verified.';

-- ----------------------------------------------------------------------------
-- 12. SECURITY DEFINER RPC: create_organization
-- ----------------------------------------------------------------------------
-- Avoids the chicken-and-egg between organizations INSERT policy and
-- organization_memberships INSERT policy when bootstrapping a new team org.
-- The backend calls this RPC instead of two separate INSERTs.

CREATE OR REPLACE FUNCTION public.create_organization(_name TEXT)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    new_org_id UUID;
    caller_id UUID := auth.uid();
BEGIN
    IF caller_id IS NULL THEN
        RAISE EXCEPTION 'create_organization requires an authenticated user';
    END IF;
    INSERT INTO public.organizations (name, is_personal, created_by)
    VALUES (_name, FALSE, caller_id)
    RETURNING id INTO new_org_id;

    INSERT INTO public.organization_memberships (organization_id, user_id, role)
    VALUES (new_org_id, caller_id, 'owner');

    RETURN new_org_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_organization(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_organization(TEXT) TO authenticated;
